apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "flask.name" . }}-sa
  namespace: {{ .Values.Namespace }}

  labels:
{{ include "flask.labels" . | nindent 4 }}

automountServiceAccountToken: false